version: "3.9"
services:
  web:
    image: node:16.10-alpine3.11
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      NODE_ENV: development
    working_dir: /app
    command: sh -c "cd /app; yarn install; yarn run start"